"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const response_1 = require("./response");
const next_1 = require("./next");
const utils_1 = require("./utils");
globalThis.Res = response_1.Response;
globalThis.r = response_1.Response;
globalThis.next = next_1.next;
globalThis.Log = utils_1.Logger;
globalThis.Logger = utils_1.Logger;
