name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  node:
    name: Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Build gaman
        run: npm run build

      - name: Run tests
        run: npm run test

  bun:
    name: Bun
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
      
      - name: Build gaman
        run: bun run build

      - name: Run tests
        run: bun run test

  bun-windows:
    name: Bun Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Remove package-lock.json (to avoid npm lockfile conflict)
        run: Remove-Item package-lock.json -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Install dependencies
        run: bun install
      
      - name: Build gaman
        run: bun run build

      - name: Run tests
        run: bun run test
